### ISSUE TITLE
Next release/tag (v4_2)

### ISSUE THREAD

**Issue by tales-aparecida** [kernelci/kcidb-io#75]
Hi,

I was working on [cleaning some deprecation warnings](https://gitlab.com/cki-project/cki-tools/-/issues/88) in some pipelines and would benefit from a new release/tag in kcidb-io after you have fixed the [jsonschema.Draft7Validator.FORMAT_CHECKER](https://github.com/kernelci/kcidb-io/commit/109e521b720116d5fba9950db83d4465920648b8).

If you happen to have any milestones you want to reach before settling on a new tag, I might be able to help 😬 

Thanks

**Comment by tales-aparecida** [comment]
We talked about creating a new tag to include the [v4.2 schema]( https://github.com/kernelci/kcidb-io/blob/main/kcidb_io/schema/v04_02.py)

**Comment by spbnick** [comment]
Sure! There doesn't seem to be anything outstanding, really, but please test the latest `main` and see if this works for CKI. 

There's one thing I'd like to have users to transition to: it's to [use `graph` instead of `tree`](https://github.com/kernelci/kcidb-io/blob/main/kcidb_io/schema/abstract.py#L32-L34) for exploring the schema's object relations. I'm not sure if CKI is using it, but would be nice to do sometime, because it's no longer a tree but a DAG.

If everything looks OK, I can tag latest `main` with the next release, which should be `v4`.

**Comment by spbnick** [comment]
Here's the description of `graph`: https://github.com/kernelci/kcidb-io/blob/4691cd7e477083268e69e401fa6d0b6e07f76648/kcidb_io/schema/abstract.py#L126-L130

**Comment by spbnick** [comment]
According to Michael we don't need the tag anymore. Closing. Please reopen, if I'm wrong.
